### ISSUE TITLE
Assignment 1: Issue handling wrong filename

### ISSUE THREAD

**Issue by MasahiroMarkTsujimura** [xaviermartinez2012/Intro-to-Networks-and-Distriuted-Computing#7]
When the user enters the wrong file name, the program stops

**Comment by xaviermartinez2012** [comment]
Do you mean that the program "hangs" or stops execution?

**Comment by xaviermartinez2012** [comment]
I remember testing this from my computer and the server PI responds with "No such file or directory" but execution continues...

**Comment by MasahiroMarkTsujimura** [comment]
it hangs on my ubuntu

**Comment by xaviermartinez2012** [comment]
Ok, will look at this tonight.

**Comment by MasahiroMarkTsujimura** [comment]
One way to solve this is to store the data from LIST request then scan through to it to see if the filename that user requested does exist in the LIST.  If the file does not exist, return to the "Enter LIST, RETR, or QUIT" message. One problem I see with this method is that the user has to request LIST from the server even if they already know the file name (wastes data transfer and causes a slight delay)

**Comment by xaviermartinez2012** [comment]
I am working on making sure that user first, explicitly, enters "RETR". Within the RETR functionality, I plan on using the server PI response as a mean to control the flow of the program. With an "accepted" error code we go ahead and connect to the DTP server otherwise we start the while loop over.

**Comment by xaviermartinez2012** [comment]
Fixed with commit ^^^ to master on 2/2/17
